### ISSUE TITLE
Cannot report file fragments when using hotspot

### ISSUE THREAD

**Issue by arichardson** [KDAB/perfparser#3]
I just tried using hotspot and it looks great but for some reason it will not display a callgraph when I use it on lld.
I get lots of errors like this printed on the console: `failed to report ElfInfo{localFile="/local/scratch/alr48/cheri/output-stable/sdk/bin/lld", isFile=true, originalFileName="lld", originalPath="/local/scratch/alr48/cheri/output-stable/sdk/bin/lld", addr=1d01000, len=35164160, pgoff=28315648, } : Cannot report file fragments`

However, if I do a perf report I get a nice graph:
```
# To display the perf.data header info, please use --header/--header-only options.
#
#
# Total Lost Samples: 0
#
# Samples: 12K of event 'cycles'
# Event count (approx.): 11059346320
#
# Children      Self  Command  Shared Object        Symbol                                                                                         
# ........  ........  .......  ...................  .........................................................................................................................
#
    21.79%     0.00%  ld.lld   [unknown]            [.] 0xcccccccccccccccc                                                                                                   
             |
             ---0xcccccccccccccccc
                |          
                |--21.78%-- (anonymous namespace)::MIPS<llvm::object::ELFType<(llvm::support::endianness)0, true> >::isPicRel
                |          0x100000000001
                |          |          
                |          |--8.01%-- lld::elf::MergeInputSection::getOffset
                |          |          |          
...
...
...
```

It seems like perf is also slighly surprised since there is this weird
`21.79%     0.00%  ld.lld   [unknown]            [.] 0xcccccccccccccccc`.

**Comment by milianw** [comment]
Yep, I'm also suffering from this regularly and actually was looking into this just the other day. Sadly, no clue on how to resolve it just yet. 

What distro are you using? Is it 100% reproducible for you with lld? That could help me figuring this out, since so far the issue is somewhat random for me.

If you have the time, could you also try to run a perf built with libdw instead of libunwind (the default) and see how that fares? We also use libdw in perfparser, so I'd like to see if this is an issue only in perfparser or also happens in perf+libdw.

Also note that I'll move this issue over to hotspot, as I want to track all issues there centrally.
